server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leanhthanhtai/spring-config-server-kiemtra-cuoiky.git
          clone-on-start: true